<h1>Pessoas</h1>

<a class="btn btn-primary" href="/pessoas/save">Nova Pessoa</a>
<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Nome
            </th>
            <th>
                CPF
            </th>
            <th>
                <!-- Ações -->
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($pessoas as $pessoa) { ?>
            <tr>
                <td><?= $pessoa->id; ?></td>
                <td><?= $pessoa->nome; ?></td>
                <td><?= $pessoa->cpf; ?></td>
                <td>
                    <a href="/pessoas/save/<?= $pessoa->id; ?>">
                        <i class="glyphicon glyphicon-pencil"></i>
                    </a>
                    <a href="/pessoas/delete/<?= $pessoa->id; ?>">
                        <i class="glyphicon glyphicon-trash"></i>
                    </a>
                </td>
            </tr>
            <tr>
                <td>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Nome Pet</th>
                                <th>Tipo</th>
                                <th>Raça</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($pessoa->pets as $pet) { ?>
                            <tr>
                                <td><?= $pet->nome; ?></td>
                                <td><?= $pet->tipo; ?></td>
                                <td><?= $pet->raca; ?></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </td>
            </tr>
        <?php } ?>
    </tbody>

</table>
