<h1>Pets</h1>

<a class="btn btn-primary" href="/pets/save">Novo Pet</a>

<table class="table">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Tipo</th>
            <th>Raça</th>
            <th>Dono</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($pets as $pet) { ?>
            <tr >
                <td><?= $pet->nome; ?></td>
                <td><?= $pet->tipo; ?></td>
                <td><?= $pet->raca; ?></td>
                <td><?= $pet->dono->nome; ?></td>

            </tr>
        <?php } ?>
    </tbody>
</table>